apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-node
  template:
    metadata:
      labels:
        app: backend-node
      annotations:
        redeploy: "v3"
    spec:
      containers:
        - name: backend-node
          image: alex148m/backend-node:latest
          ports:
            - containerPort: 3000
          env:
            - name: DEMO_VERSION
              value: "v3"
      imagePullSecrets:
        - name: dockerhub-secret